### ISSUE TITLE
Resolution lost in cryo-EM

### ISSUE THREAD

**Issue by aalhossary** [biojava/biojava#1000]
Several entries have the resolution value set to **99** when obtained from PDB and 0 when obtained from mmCif.

Each was cryo-EM with resolutions in the range 3.35 - 3.8 Å.

4 examples are 
(**3j8h**, **3jaj** (available only in mmCIF).
**6hu9**, **7o3e** (available as PDB files).

By experimenting, I found that 
- The PDB entries have the resolution reported in **REMAK 2** (not parsed at all) and in **REMARK 3** (using a format not recognized by the `PDBFileParser`). --> they are left as the default resolution value (**99**).
- The mmCif entries have the `.` value in the `_refine.ls_d_res_high` field, which indicates that the value [_may be used to identify that there is no appropriate value for the item or that a value has been intentionally omitted_](https://mmcif.wwpdb.org/docs/tutorials/mechanics/pdbx-mmcif-syntax.html#:~:text=A%20period%20(.)%20may%20be%20used%20to%20identify%20that%20there%20is%20no%20appropriate%20value%20for%20the%20item%20or%20that%20a%20value%20has%20been%20intentionally%20omitted.) (I don't know why omitted) --> when the period (`.`) is parsed into `float`, it is wrongly parsed as (**0.0**)

**Comment by aalhossary** [comment]
Proposed solutions:
- Proper parsing of the **PDB** entries. (I will submit a PR)
- Contacting someone (?) to indicate some value in the **mmCif**  entries `_refine.ls_d_res_high` field
- Fixing how the period (`.`) is dealt with in this field, unless this **ZERO** is an intended outcome. Is it?

**Comment by josemduarte** [comment]
> The PDB entries have the resolution reported in REMAK 2 (not parsed at all) and in REMARK 3 (using a format not recognized by the PDBFileParser). --> they are left as the default resolution value (99).

One issue here is that the PDB format doesn't seem to be standardised regarding __REMARK 3__. See:
https://www.wwpdb.org/documentation/file-format-content/format33/remark3.html . So parsing it would be nice, but won't necessarily cover all cases. Anyway I suppose that's a problem of the legacy PDB format and another reason to continue decreasing its usage.

> mmCIF resolution parsing for EM case

The real issue here is that there's a different field to get the resolution for cryoEM method: `_em_3d_reconstruction.resolution`. So in principle the mmCIF parser should be using the resolution value from there if available (which would indicate that the method is EM). The field `_refine.ls_d_res_high` is for diffraction methods only.

**Comment by aalhossary** [comment]
I submitted a pull request to fix that. 
However, a new question arises: 
There are cases where the resolution is unknown (the `_em_3d_reconstruction.resolution` value is a `?`). In that case, should the default value be **0.0** or **99**?

Some examples include
- 2FTE
- 3JC8
- 3JC9
- 6EDT
- 6ZTS
- 6ZTY
- 6ZTZ
- 7EIZ
- 7MBS
- 7MBT
- 7MBU
- 7O2W

**Comment by josemduarte** [comment]
I suppose it'd be ok to stay with 99, since that's the expected behaviour looking at the code. The rationale behind it is that filtering on resolution would work as naturally expected (resolution<2 would filter out all the unknown resolution cases).

In any case, it'd be good to document it. Could you add a brief explanation to `PDBHeader.getResolution()` ?

**Comment by aalhossary** [comment]
Done.
