### ISSUE TITLE
Issue of Biojava protein comparision tool

### ISSUE THREAD

**Issue by B246371-2023** [biojava/biojava#1096]
Dear Biojava team,

When I was using the Biojava tool to perform tertiary structure alignment of proteins recently, I found that there was a problem of missing parameters in the protein comparison tool, which is important for automation.

**Insufficient parameter occurs when calling FatCat program.**
Biojava 7.1.1/4.0.0 -alignPair function failure 
I read the help manual. According to the documentation and the past command line examples, I entered the command line as follow and it should not be missing any parameter. However in the latest version and all versions after 6.0.0 can not use this parameter -alignPair, may I ask is it invalid?
![image](https://github.com/biojava/biojava/assets/145386695/63ba2c4a-9763-4855-bc41-0114d98a08bc)
![image](https://github.com/biojava/biojava/assets/145386695/9d176cb5-1eeb-4c51-b439-64fcb2d96436)

**One more question of invalid of autoFetch function invalid in earliest version comparison tool**
Biojava 7.1.1(latest version) autoFetch parameter run success
![image](https://github.com/biojava/biojava/assets/145386695/6ff7c966-bd73-4264-929d-a92305f9d7ca)

But Biojava 4.0.0 autoFetch parameter run failure— time out
![image](https://github.com/biojava/biojava/assets/145386695/14b8e35d-6ed7-45da-ad1f-f70d7f0c9c8c)

I think maybe because the FatCat update and then the network protocal maybe different and the autofetch function need update also. So may I ask why 4.0.0 can not be used but latest version can be used?

Looking forward to your guidance and suggestions on these matters.  Many thanks for any advice you can give.

**Comment by josemduarte** [comment]
Thanks for reporting and sorry for the delay. It looks like `-alignPairs` was a victim of the transition to version 7. At that point the RCSB PDB discontinued the database service behind this software and much code related to DB searches was deleted. However, it is very possible that `-alignPairs` was deleted in mistake. 

I think it should be possible to fix. I'm going to have a look into it.

Regarding the problems with BioJava 4.0.0 autoFetch, I suppose that's due to the software trying to get the PDB files via an address that has also being discontinued (https://ftp.rcsb.org)

**Comment by josemduarte** [comment]
@B246371-2023 coud you check #1098 when you have some time? If no comments by next week, then I'll merge
