### ISSUE TITLE
Phylip Parser

### ISSUE THREAD

**Issue by sbliven** [biojava/biojava#122]
Add a parser for [Phylip](http://evolution.genetics.washington.edu/phylip.html)

_Suggested for [GSoC 2012](http://biojava.org/wiki/Google_Summer_of_Code_2012)_

**Comment by lafita** [comment]
The **Phylip** format can refer to the MSA format, like FASTA format (see [here](http://evolution.genetics.washington.edu/phylip/doc/sequence.html) the format explanation) or to a distance matrix format (see [here](http://evolution.genetics.washington.edu/phylip/doc/distance.html) the format explanation). I guess @sbliven that the discussion was about the MSA format. I have seen that **forester** contains methods to write the *DistanceMatrix* object as a **Phylip** format, but I could not find a parser for the MSA format. 

In the documentation of their application (see [Input and Output Formats section](https://sites.google.com/site/cmzmasek/home/software/archaeopteryx)) they do not list PHYLIP as a supported format, but I tried the application and it can read phylip MSA formats, so there must be a parser in the **forester** package.

Since **Phylip** seems to be a general format for MSA storage (but less powerful than FASTA), is there a need to provide a parser in the **core** module of biojava, or using the **forester** one only for the **phylo** module is enough? Since we had already an implementation it would be just a design issue.

**Comment by lafita** [comment]
In the **forester** library:
Probably the [GeneralMsaParser](https://github.com/cmzmasek/forester/blob/master/forester/java/src/org/forester/io/parsers/GeneralMsaParser.java) class is used to parse **Phylip** MSA formats (the documentation is poor).
There is also a [SymmetricalDistanceMatrixParser](https://github.com/cmzmasek/forester/blob/master/forester/java/src/org/forester/io/parsers/SymmetricalDistanceMatrixParser.java) class for symmetrical distances in **Phylip** format.
