### ISSUE TITLE
RotationAxis jmol looks wrong

### ISSUE THREAD

**Issue by sbliven** [biojava/biojava#129]
Double check that RotationAxis is visualized properly for all cases. Specifically:
* Translation vector should go through the center of mass (e.g. 1aew)
* Large off-center insertions are ignored (e.g. 2j8s_A_1-37,A_329-517)

**Comment by andreasprlic** [comment]
Is this still a problem in the current code base?

**Comment by lafita** [comment]
This issue is about the internal symmetry axis. The axes are actually not wrong. 

**1aew** has what we call (un-officially) slip symmetry, which means that helices align with itself one turn down. The axis does not go through the center of mass because there is a small rotation associated with the axis. Thus, the axis is located at the center of the rotation. It can be appreciated here: http://source.rcsb.org/jfatcatserver/showSymmetry.jsp?name1=1aew&matrix=sdm&seqWeight=0.0

On the other hand, 2j8s looks fine to me. We fixed a numerical error with 2-fold axis long ago. Because the structure has 2-fold symmetry I am guessing it was solved. 

This issue can be closed.
