### ISSUE TITLE
@SupressWarnings overused and/or used incorrectly

### ISSUE THREAD

**Issue by benjamintboyle** [biojava/biojava#185]
As of 01 Oct 2014, there are 272 instances of @SupressWarnings throughout the biojava project. Many of the instances are programmatic issues that should not be suppressed. Recommend adding comment/javadoc as to the reason for suppression, otherwise the @SupressWarnings should be removed and the warning fixed programmatically.

**Comment by sbliven** [comment]
Part of the problem here comes from differences in Eclipse's warning levels. For instance, I introduced some SuppressWarnings that appear unneccessary unless you have 'Signal overriding or implementing deprecated method' set. Those were probably a bad idea-we should only suppress warnings which appear with default compilation settings.

**Comment by andreasprlic** [comment]
This should not prevent us from making the BioJava 4.0.0 release soon.
