### ISSUE TITLE
Drop support for File-based Biological assemblies

### ISSUE THREAD

**Issue by sbliven** [biojava/biojava#226]
Is there any reason to continue using the PDB-provided biological assembly files? It makes more sense to me to generate them directly from the files.

**Comment by josemduarte** [comment]
:+1: 

In addition there's an important problem: PDB-provided biological assembly files are not available in PDB format anymore for large entries, but only in mmCIF format.

Instead of also implementing reading of PDB-provided mmCIF bio assemblies, I think it is a good idea to simply default to generate the biological assemblies from the headers (biojava has already code for that in `org.biojava.bio.structure.quaternary.io`) and drop the support for bio assembly files reading altogether.

**Comment by pwrose** [comment]
+1 Taking out that functionality would clean up the IO code quite a bit.

On Thu, Jan 8, 2015 at 1:52 AM, Jose Manuel Duarte <notifications@github.com
