### ISSUE TITLE
Downloading of PDB/mmCIF files trough AtomCache is slow and fails often

### ISSUE THREAD

**Issue by josemduarte** [biojava/biojava#227]
I am running a test that requires downloading of 1000 PDB and 1000 mmCIF files via AtomCache. 
There's 2 problems:
- the downloads seem to be extremely slow if I compare to equivalent rsync downloading
- the download is breaking every ~20-30 files with a timeout or some other connection interruption

After looking at the current code, there are a few things that seem to be wrong with the downloading, e.g. it seems that the gzip stream is first uncompressed and then compressed again before being written to disk. Most likely the buffering can also be done better. I didn't look in so much detail but there are definitely things to improve.

**Comment by josemduarte** [comment]
This can be related to some of the travis failures we often see, or at least the travis failures are happening more often because of this.

**Comment by sbliven** [comment]
The speed issue should be improved by optimizing methods in `FileDownloadUtils` to minimize gzip compression/uncompression.

Improving the reporting of FTP connection errors & status codes might shed light on the second problem. I think this bug has been around a long time but passed off as flukes and concurrency problems (e.g. doing the CE-Symm census with @dmyersturnbull). It will be great to crush it finally.

**Comment by andreasprlic** [comment]
interesting observation. There is no firewall protection for too many downloads on the ftp servers. However there is firewall rule protecting the web site. If you use the DownloadChemCompProvider it fetches the files form the website rather than ftp, since the files are no avail from there. It could be that many fetches in a short period of time triggers a firewall rule. What Chemical component provider are you using? I wonder if the problem goes away if you switch to the AllChemCompProvider.

There is now also a new mechanism to access the FTP site. We enabled the http protocol to access all files. This can be used as a work around the Java FTP client problems that @sbliven mentions. http://ftp.wwpdb.org/ is now the "same" as ftp://ftp.wwpdb.org/

**Comment by josemduarte** [comment]
Thanks @andreasprlic for the comment. I think after all this can be more a firewall issue than anything else. I'm specially suspicious of our local firewall, which filters quite aggressively. I've made an experiment of switching to the http:// urls you mention and... I get a speed increase of 2x !!

**Comment by josemduarte** [comment]
What about defaulting to the http protocol in `AtomCache`? I think it is the protocol that will be most available behind even the most radical firewalls.

**Comment by andreasprlic** [comment]
yes, we should switch that, now where it is possible. That definitely will also be a workaround for the multi threaded download problems we had with the Java FTP client library...

**Comment by josemduarte** [comment]
I can confirm now by using my ISP connection that I also gain 2x in download speed by changing ftp to http. So at least that rules out that the problem is at the firewall on the client side. The firewall on the server side (PDB) could still have something to do with it. Anyway my main suspect now would be the differences in how java handles the ftp/http protocols

**Comment by josemduarte** [comment]
This is a good read

http://www.javaworld.com/article/2073325/java-app-dev/java-ftp-client-libraries-reviewed.html

**Comment by andreasprlic** [comment]
sounds like we should re-write any FTP access to use http instead...

**Comment by sbliven** [comment]
Since we're all testing the same files, the HTTP versions should hit memcache on the server side, right? Is there an equivalent caching layer in the FTP server? If not, could that account for part of the speedup, or is the server-side IO negligible compared to the network time for these files? The average gzipped mmcif file is 241.6 KiB.

**Comment by josemduarte** [comment]
My latest pull request solves some of these issues, so I'll close this for now.

Regarding the connection breaking, it looks more like a temporary glitch in the server, I haven't seen it happening again in the last couple of days

**Comment by andreasprlic** [comment]
It is likely that the apache instance on top of the ftp servers is doing some caching and that this contributes to the speed gains. Also FTP communication requires more back and forth with the client and therefore by definition is likely to be slower.

**Comment by sbliven** [comment]
How much time does the performance test take? 20 structures * a few seconds each? Since it's not really asserting anything important, I'd suggest renaming it so it doesn't get run by maven.

**Comment by josemduarte** [comment]
A minute or so (depending on bandwith and hardware of course). Strictly speaking it is not a test, it's not asserting anything... I put it there lacking a better place for it ;)

**Comment by sbliven** [comment]
Ah, it's excluded in the pom. perfect.
