### ISSUE TITLE
Please vote: Rename module names

### ISSUE THREAD

**Issue by sbliven** [biojava/biojava#242]
Along with the package names discussed in ~#240~ #245, this [thread](http://mailman.open-bio.org/pipermail/biojava-dev/2014-October/007842.html) also discussed renaming the modules and maven artifact IDs.

**Question:**
> Should modules and maven artifact IDs be renamed to remove the **biojava3** version?

Option in favor of renaming (+1):
* Change all modules to use `biojava-` as a prefix, e.g. `biojava-core` and `biojava-integrationtest`

Option for partial renaming (-1):
* Change all modules to use `biojava3-` as the prefix *to match the package name*. Only effects the integrationtest and protein-comparison-tool packaging modules, so won't impact any downstream projects

*Clarification: If the consensus from #245 is to update package names for each version (biojava4, biojava5, etc), then the module names will also be updated.*

Option for no renaming (-2):
* Leave everything as it is.

**Comment by sbliven** [comment]
-1 Partial renaming

**Comment by josemduarte** [comment]
+1

**Comment by andreasprlic** [comment]
+1

**Comment by phidias51** [comment]
+1

**Comment by heuermh** [comment]
To clarify, currently biojava-legacy on Maven Central is using coordinates such as
```xml
  <groupId>org.biojava</groupId>
  <artifactId>core</artifactId>
  <version>1.9.1</version>
```
There were also biojava3 artifacts released third-party to Maven Central using coordinates such as
```xml
  <groupId>org.biojava</groupId>
  <artifactId>biojava3-core</artifactId>
  <version>3.0</version>
```
All other biojava version 3.x releases were only released to the biojava maven repository.

There was at least one conflict between the biojava-legacy build and biojava3, which needed to be resolved by removing the das module from biojava-legacy, see https://github.com/biojava/biojava-legacy/commit/8380b19a482a968a30e7392f94443a1c891ff9e2.

The current git head is using coordinates such as
```xml
  <groupId>org.biojava</groupId>
  <artifactId>biojava3-core</artifactId>
  <version>4.0.0-SNAPSHOT</version>
```

If there weren't already artifacts released to Maven Central under artifactId prefix ```biojava3-``` then I think I'd be ok moving backwards so-to-speak with e.g. ```biojava-core``` for version 4.0.  Unfortunately they were so I think at this point we can't go backwards.

Thus I vote -1 to change all modules to use ```biojava3-``` as the prefix.
 or
-3 change all modules to use ```biojava4-``` as the prefix.

**Comment by pwrose** [comment]
+1 for major renaming of package names. If we want to get more new users, a clean naming scheme is essential. Current developers can deal with minor inconveniences to enable benefits in the future.

**Comment by andreasprlic** [comment]
@heuermh is the rule that we can't go backwards something imposed by Maven Central, or is this just by convention? Since this will be the first time that we are officially pushing to MC I think we should be free to chose whatever artifactId we are most comfortable with. The version number is the place to specify the actual version and not groupId nor artifactId ...

**Comment by dmyersturnbull** [comment]
+1 Users will have to update their POMs anyways.

**Comment by paolopavan** [comment]
-3
Agree with @heuermh .
Moreover will allow a good degree of backward compatibility merging bug fixes and and patches on biojava4 also with compatible source in biojava3, if this is the main concern.
By the way, biojava have already did it in respect of legacy package.

**Comment by sbliven** [comment]
I've added a clarification to the options in the original post. Votes for @heuermh's "-3" option will be bundled into the -1 votes, pending the decision for package renames. Lets keep them consistent.

**Comment by andreasprlic** [comment]
I hear the vote for -3 but a majority has voted +1, thus suggesting that we should push the following coordinates:

```xml
  <groupId>org.biojava</groupId>
  <artifactId>core</artifactId>
  <version>4.0.0</version>
```

**Comment by heuermh** [comment]
Shoot, I don't want to be a pain, but here is an actual use case that might demonstrate the problem:

We have some code here that builds on the biojava-legacy alignment package
https://github.com/nmdp-bioinformatics/ngs/tree/master/align/src/main/java/org/nmdp/ngs/align

so we have a dependency on ```org.biojava:alignment:1.9.1```
https://github.com/nmdp-bioinformatics/ngs/blob/master/pom.xml#L86
https://github.com/nmdp-bioinformatics/ngs/blob/master/pom.xml#L121

Once some of the outstanding issues with the biojava3/biojava4 alignment code are resolved, I might want to add implementations based on biojava3/biojava4.  Say a ParallelBiojava4PairwiseAlignment class similar to
https://github.com/nmdp-bioinformatics/ngs/blob/master/align/src/main/java/org/nmdp/ngs/align/ParallelBiojavaPairwiseAlignment.java

Then I would want to have dependencies on both ```org.biojava:alignment:1.9.1``` and ```org.biojava:alignment:4.0.0``` from the same library, which is not allowed by Maven dependency resolution rules.

I could split the one align module into two align modules, one with a dependency on ```org.biojava:alignment:1.9.1``` and one with a dependency on ```org.biojava:alignment:4.0.0``` but then I've just pushed the problem upstream.  If another module (say tools in that repo) ends up with dependencies on both align-biojava1 and align-biojava4 then the transitive dependencies collide and stuff breaks at runtime.

This is not necessarily hypothetical, since I would actually like to add support for the biojava3/biojava4 alignment implementations if/when the issues are resolved.

**Comment by andreasprlic** [comment]
@heuermh you are never a pain and we count on your invaluable experience! You make an excellent point why what I just suggested is not a good idea. As such the jars will be described as such:

```xml
  <groupId>org.biojava</groupId>
  <artifactId>biojava4-core</artifactId>
  <version>4.0.0</version>
```

**Comment by heuermh** [comment]
ok, thanks!  I'll try now to go back to being quiet.  :)

**Comment by sbliven** [comment]
Ok, I'm in favor of closing this issue and appreciate @andreasprlic's decisiveness. I just wanted to clarify whether we plan to update the 'biojava4' part with every major release. Since #245 seems to have been resolved on keeping 'org.biojava.nbio' rather than changing stuff each version, shouldn't the artifactIds be stable too? Can we agree that biojava 5+ will also be released as 'biojava4-core'?

**Comment by josemduarte** [comment]
Again I'm all for closing this issue and thanks @andreasprlic all the efforts to do so. But I'm afraid I need to add something since there seems to be some confusion above.

At the moment biojava-legacy has these maven identifiers:
```xml
    <groupId>org.biojava</groupId>
    <!-- parent pom -->
    <artifactId>biojava-legacy</artifactId>

    <!-- modules -->
    <artifactId>alignment</artifactId>
    <artifactId>structure</artifactId>
    <!-- ... -->
```

Which means that biojava 4 and successors can use a simple naming convention, using the __`biojava-`__ prefix in the module artifacts:
```xml
    <groupId>org.biojava</groupId>
    <!-- parent pom -->
    <artifactId>biojava</artifactId>

    <!-- modules -->
    <artifactId>biojava-alignment</artifactId>
    <artifactId>biojava-structure</artifactId>
    <!-- ... -->
```
Fundamentally we have agreed to change the package namespace to something never used before (`org.biojava.nbio.*`). The new package name scheme together with the above module name scheme result in __no collisions__ at all, or am I misunderstanding something?

Additionally with all modules prefixed in this way we get a nice grouping of them in eclipse which makes our lives easy.

**Comment by heuermh** [comment]
@josemduarte yes, awesome, make it so!

**Comment by andreasprlic** [comment]
ok, a name is a name and everybody needs to updated their pom files anyways so let's use @josemduarte 's version.

**Comment by andylaw** [comment]
Sounds sensible to me.

On 29 Jan 2015, at 15:48, Andreas Prlic <notifications@github.com<mailto:notifications@github.com>> wrote:


ok, a name is a name and everybody needs to updated their pom files anyways so let's use @josemduarte<https://github.com/josemduarte> 's version.

—
Reply to this email directly or view it on GitHub<https://github.com/biojava/biojava/issues/242#issuecomment-72047222>.
The University of Edinburgh is a charitable body, registered in
Scotland, with registration number SC005336.

**Comment by agupta1989** [comment]
+1
