### ISSUE TITLE
Incorrect length calculation in AtomPositionMap

### ISSUE THREAD

**Issue by sbliven** [biojava/biojava#244]
The calcLength() methods of AtomPositionMap don't include the end residue, lead to off-by-one errors. This is particularly apparent when parsing ResidueRangeByLength objects, where "A:1-2" has a length of 1.

**Comment by sbliven** [comment]
Also the calcLengthDirectional() returns weird values. I would expect `calcLengthDirectional(a,b) = -calcLengthDirectional(b,a)` for `a,b` on the same chain. Instead it gives -1, etc.

**Comment by dmyersturnbull** [comment]
calcLength was meant to count half-inclusive, like numbers. So "A:1-2" has a length of 2 - 1 = 1. This has both advantages and disadvantages, but it should have been documented. I don't know that I'd support changing to inclusive counting while keeping the name calcLength(), but calcNumberOfResidues("A:1-2") could return 2. Alternatively, or additionally, ResidueRangeAndLength.getNumberOfResidues() for A:1-2 could return 2.

For calcLengthDirectional(), what PDB Id did you run on? It returns -1 when the chain doesn't exist in the map. It should throw an IllegalArgumentException instead, so I'll fix that. There's definitely another bug if you called calcLengthDirectional(a, b) without specifying a chain.

**Comment by sbliven** [comment]
Half-inclusive ranges only work for things with a well-defined and predictable order. That definitely doesn't apply for ResidueRanges. As it stands, there is no way to construct a range which includes the last residue!

Regarding the name, I don't see how a length method that actually returns one less than the length is anything but misleading. I'll rename it to force a compilation error, but I think calcLength needs to be deleted rather than deprecated.

Do we even need the directional versions? They're only used by symmetry's Protodomain class, which I've already horribly broken and need to rewrite.

**Comment by dmyersturnbull** [comment]
> Half-inclusive ranges only work for things with a well-defined and predictable order. That definitely doesn't apply for ResidueRanges.
Residue numbers definitely don't have a predicable order, but they're simply getting mapped to their indices in the PDB file. In "A:1-2", "1" is at position 0, and "2" is at position 1, so the length in that sense is 1. That mapping was really the idea behind AtomPositionMap, so there's some code in the symmetry project that relies on that definition.

Since it's apparent that it's at least very misleading, I'm all for deleting it. I'm fine with any solution other than keeping the name calcLength() and changing its behavior.

> Do we even need the directional versions?
No, feel free to remove it.
