### ISSUE TITLE
Please vote: Major refactoring of package names (2nd attempt)

### ISSUE THREAD

**Issue by josemduarte** [biojava/biojava#245]
See original vote in #240 . Now we are extending the vote to include all proposed solutions.

Please vote on one of these solutions. If you are happy with more than one of them, then write down all solutions you like sorted from most ideal to least ideal (e.g. 3, 2, 1), I think that can help taking a final decision.

1. __Keep existing situation__: a mix of `org.biojava3.modulename.*` and `org.biojava.bio.structure.*` (in structure and structure-gui modules)

2. __In structure/structure-gui modules rename `org.biojava3.*` to `org.biojava.bio.structure.*`__ so that all other modules are `org.biojava3.*` while structure/structure-gui are `org.biojava.bio.structure.*`, proposed by @dmyersturnbull 

3. __Rename `org.biojava.bio.structure.*` to `org.biojava3.structure`__ : i.e. keep the biojava3 naming but making the whole project consistently use the `org.biojava3.modulename.*` scheme

4. __Rename all packages to `org.biojava.modulename.*`__ , original solution proposed by @andreasprlic. This has issues with transitivity, as [explained](http://mailman.open-bio.org/pipermail/biojava-dev/2014-October/007847.html) by @heuermh 

5. __Rename all packages to `org.biojava4.modulename.*`__ and do the same for every major release, proposed by @paolopavan 

6. __Rename all packages to a new namespace that was never used before, e.g. `org.biojavax.modulename.*`__ : this avoids the transitivity issues and avoids renaming at every major release. __UPDATED__ apparently `org.biojavax.modulename.*` was actually used before (see @heuermh 's comment below), a better name proposed by @sbliven is __`org.biojava.nbio.modulename.*`__

**Comment by josemduarte** [comment]
6, 4, 5

**Comment by sbliven** [comment]
I vote 4.

**Comment by paolopavan** [comment]
5.
Already explained why here https://github.com/biojava/biojava/issues/240#issuecomment-71466623

**Comment by jgrzebyta** [comment]
Thanks @paolopavan for info.

I vote 4, 5

**pro4** New release should be backward compatible: new release should at lest cover previous functionality. Changes in API would be accepted than.

**pro5** However I understand that some projects are quite complex and developers don't like to change everything just because changed API. Different namespace is the simplest option in that case. But also jar files should be renamed as well.

**Comment by dmyersturnbull** [comment]
2, 4

2 because it won't require users to change (almost) anything and seems hands-down better than 1.

4 because if we're going to do this, let's go all the way. From what I understand, only Biojava 1 presents a namespace conflict with the packages we'd rename to. Thus for a version conflict, dependencies would need to use Biojava 1. org.biojava.modulename is the natural choice, and it won't force users to change their imports for every major release.

**Comment by heuermh** [comment]
5, 3, 1

As the release manager for biojava-legacy, which deploys to the Maven Central repository and still sees occasional releases, I strongly argue that we cannot do 4.

We shouldn't do 6 either as described above because ```org.biojavax``` as a package name is already in use.  See http://www.biojava.org/docs/api1.9.1/overview-summary.html  Are there other suggestions?

**Comment by pwrose** [comment]
4,6,5

**Comment by aalhossary** [comment]
5, 6, 4

 

Amr

**Comment by andreasprlic** [comment]
Ok. people seem to vote in terms of refactoring 4,5, or 6 here. Let's put this on the roadmap for 5.0 then. (I take #240 as "not now").

**Comment by aalhossary** [comment]
May I know where is the Roadmap? 

 

I am asking because I wanted to propose some major changes in class hierarchy and relations for this major release but I couldn’t catch it in time.

 

Amr

**Comment by andreasprlic** [comment]
we are currently using the github "milestones" for flagging tickets and assigning them to certain releases.

**Comment by sbliven** [comment]
I think we need to defer to @heuermh on the ineligibility of 4 due to maven, as well as the org.biojavax namespace.

I change my vote to a strong 3 (biojava3), as I really dislike the prospect of changing this every version. The version field should be the only thing you have to update to change versions, not the package names and everything. I always hated how commons-collections and such did that (sorry, @paolopavan).

I'd also be OK with 6. I like the name org.biojava.nbio, which keeps the tie to our domain name as suggested for package names, and parallel's Java's nio for "new io". Jose had a nice list of suggestions on the mailing list, which I will not reiterate for fear of introducing yet more options.

**Comment by sbliven** [comment]
@andreasprlic #240 was inconclusive, and was supplanted by this. I would really like to close this discussion now. No one has voted for 1 ("not now") except as a final preference. I think the 4.0.0 milestone is appropriate.

**Comment by josemduarte** [comment]
I agree with @sbliven, why not closing this chapter now that the discussion is alive and fresh? If we have to come back to this in the 5.0 release, everything will have been forgotten and a whole new discussion will be needed. Let's close this now and forget about it forever. 

I also liked the point raised by @pwrose in #242 : a clean and consistent naming scheme is essential in order to attract potential new users and developers, the sooner we have a clean naming scheme the better.

Solutions 6,5 or 3 will do the job (excluding 4 because of the major concern of @heuermh ). If 6 is decided I'd also support the `org.biojava.nbio.*` naming that @sbliven proposes.

**Comment by paolopavan** [comment]
There is one more important consideration that comes to me late. Biojava
distribution comes in modules which are currenlty named as biojava3-core,
biojava3-phylo and so on. Since they cross reference and can be downloaded
separately, I can see the need to keep them syncronized across major
version to avoid confusions and incompatibility.
It is better that this will be evident in the name and I see this one point
in favour of 5. If not in the namespace, at least in jar name (that would
anyway silently generate runtime errors in case of mismatch). Sorry
@sbliven! :-)

Just I want to remember that since we are talking about *major releases*,
they are *not* backward compatible by definition, as stated by semantic
versioning. We should not try to make them so, it is a non sense, programs
that use biojava will fail at runtime for some unpredictable reasons. We
could at least try to import bug fixes in older versions if we want
backwards compatibility.

Don't misunderstand me, this does not want to be any kind of harassment, it
is just put some issues on the table and it is just my opinion, please
correct me if I'm wrong.
And I will stop bothering you now! :-D

2015-01-28 11:06 GMT+01:00 Spencer Bliven <notifications@github.com>:

**Comment by sbliven** [comment]
@paolopavan Your opinions are definitely valued here! You are making a great contribution to the discussion, and are bothering no one.

I agree that we *can* rename everything for each major version, as suggested in 5, and that it would still be consistent with semantic versioning practices. I just feel like, going forward, we're going to release major changes rather frequently, and going from 4.x.x to 5.x.x should be roughly as easy as going from 3.0.7 to 3.0.8. You expect things to break, but it's not like moving from 1.9.1 to 3.x.x where the whole API is different.

**Comment by andreasprlic** [comment]
ok, agreed, let's try to conclude the discussion while it is hot.

I vote for 2, 5

here my thoughts:
- 4, and 6, are off the table, due to @heuermh 's argument. 

- We should try to be backwards compatible, if it is easy, but also not hesitate to break compatibility if needed. (the case for 2 and against 3)

- It is weird to have biojava3 package names in a v.4 release (in support of 5)

- Many of the modules have not seen any change in their functionality and API, so it would be against the "don't break backwards compatibility" rule to change their package names (against 5)

- One can argue if a package name change is really breaking compatibility, since such a change can easily get fixed by the IDE. (in support of 5)

**Comment by andreasprlic** [comment]
Here the sum of the current votes:
1: 1
2: 2
3: 3
4: 4
5: 7
6: 3

**Comment by andylaw** [comment]
Democracy is a fine thing, but effectively making developers switch to using a completely different library every time you do a major release is utter madness in my opinion. They will hate you for it and will cling to the old versions for as long as possible, thus increasing your worries about backwards compatibility as you try to move forwards.

Please don’t do 5. (at least, if you do 5, don’t do the "and do the same for every major release” bit which is the part that really worries me)

Later,

Andy



On 28 Jan 2015, at 17:58, Andreas Prlic <notifications@github.com<mailto:notifications@github.com>> wrote:


Here the sum of the current votes:
1: 1
2: 2
3: 3
4: 4
5: 7
6: 3

—
Reply to this email directly or view it on GitHub<https://github.com/biojava/biojava/issues/245#issuecomment-71882625>.
The University of Edinburgh is a charitable body, registered in
Scotland, with registration number SC005336.

**Comment by heuermh** [comment]
@andylaw what is wrong with clinging to old versions for as long as possible?

Open source projects do well when they [welcome both evolutionary and revolutionary changes](http://incubator.apache.org/learn/rules-for-revolutionaries.html).  We just need to make sure one doesn't clobber the other.

**Comment by andreasprlic** [comment]
I do share Andy's concern about having to rename package with every major release. This combined with the threat to change major version numbers more often than previously does not make this very attractive. We do need an option 7 here: Use ```org.biojava.nbio.modulename.*``` as the new naming convention for all packages.

**Comment by emckee2006** [comment]
Isn't that the same as option 6?

**Comment by andreasprlic** [comment]
Initially 6 was for org.biojavax. Which had issues.

**Comment by emckee2006** [comment]
Ok I was reading that as just an example name, not the definite name in 6

**Comment by andylaw** [comment]
On 28 Jan 2015, at 19:37, Michael L Heuer <notifications@github.com<mailto:notifications@github.com>> wrote:


@andylaw<https://github.com/andylaw> what is wrong with clinging to old versions for as long as possible?


Nothing at all when it is a conscious choice rather than the path of least resistance. The danger to Biojava is that you are best served by having as few users as possible using your older versions. Make it difficult to keep up with the latest version and you’ll probably find that your uptake of the new versions is much lower than you would want.

Later,

Andy
The University of Edinburgh is a charitable body, registered in
Scotland, with registration number SC005336.

**Comment by andreasprlic** [comment]
OK, it is getting time to conclude this thread. After considering the arguments from all sides I would like to  move forward like this:

After the code freeze I will refactor all package names to follow the ```org.biojava.nbio.modulename.*``` convention. This is a variation of suggestion 6, which had some support and it seems that the majority should find this acceptable.

The new namespace will offer
- consistent naming across all modules
- no more biojava3 names, when project version is 4
- no renaming required for future major release versions
- has not been used previously

To mitigate backwards incompatibility, we will document clearly how to run ```Optimze Imports``` in an IDE. This will allow anybody doing an upgrade to quickly migrate a whole project.

Let's try to keep comments to this brief, ideally only if you want to express a major concerns about this.
