### ISSUE TITLE
mmCIF parsing support for missing CONECT ChemComp information.

### ISSUE THREAD

**Issue by larsonmattr** [biojava/biojava#341]
The SimpleMMcifConsumer does not create use Structure.setConnections to create a CONECT record list during MMCIF parsing.  It does have addBonds(), but this will create bonds for all amino acids, nucleotides, etc.  

There is already existing functionality to pull ChemComp records for a ligand that can be used to build the connections information to replicate the CONECT records of PDB files.  

BioJava should add to the SimpleMMcifConsumer the ability to make CONECT bonds only for the ligands, build from ChemComp data, without needing to create bonds for standard residues like amino acids and nucleotides.

**Comment by josemduarte** [comment]
So what about the inter-residue connections annotated in `_struct_conn` within the mmCIF file itself? I think we should also parse those and add them to the relevant bond data structures, shouldn't we?

**Comment by larsonmattr** [comment]
For the issue 343 (ssbonds), the implementation that has been started parses _struct_conn limited to looking for disulfide bonds.  This task could more generally parse bond information of _struct_conn for the bond information stored within the mmCIF.  

Generally, it appears that mmCIF files in the protein databank are absent the ligand bonds that PDB files contained leading to the approach using ChemComp groups to grab this information.  

Parsing _struct_conn should be also implemented to get any additional bond information contained in the mmCIF.

**Comment by andreasprlic** [comment]
about the ligand bonds: these are available through the chemical component dictionary. It can be accessed in BioJava by using the AllChemCompProvider, or the DownloadChemCompProvider (depending on your use case).

**Comment by andreasprlic** [comment]
Thanks for the patch!

**Comment by josemduarte** [comment]
I am revisiting this again and have just realised that we did have bonds parsing before this issue. The information was stored into the `Atom` objects (through `getBonds`) but wasn't available in the `Structure` object via `getConnections()`. The class `BondMaker` was doing all the work, so the new `LigandConnectMaker` introduced in #379 is redundant.

I would propose to simply deprecate `Structure.getConnections()` because it's a legacy representation too tied with the CONECT representation of PDB files. `Atom.getBonds()` does a much better job. I would then also remove `LigandConnectMaker` so that we are sure we don't do the bonds parsing twice.

If there's nothing against this, I'll submit a pull request to do as described above.

**Comment by josemduarte** [comment]
Looking again at the original description of the issue, @larsonmattr expresses concern that the existing implementation was doing peptide and nucleotide bonds as well as intra residue bonds. I don't see a big issue there: the peptide/nucleotide bond list will be quite small compare to the list of intra-residue bonds, so in terms of efficiency memory-wise there's little to gain. Compute-wise n-1 distances need to be calculated (for n residues).

If that computational overhead is a concern, we could simply make that a file parsing parameter to avoid it.

**Comment by josemduarte** [comment]
I'm trying now to rationalise all the bonds code and have also realised that the `SSbond` class is a legacy tied to the representation in PDB files. I would then advocate for a change in the `Structure` interface so that `Structure.getSSBonds` returns a `List<Bond>` instead of a `List<SSBond>` as it does now. I'll include that in my pull request if no one disagrees.

**Comment by andreasprlic** [comment]
+1

**Comment by larsonmattr** [comment]
Jose, the original concern for CONECTs was describing the bonds for ligands
that is missing in mmCIF.  Ideally, what was hoped for was equivalence
between for the data regardless of reading a PDB or an mmCIF.  It would be
nice if there was an equivalent for the mmCIF where is only the
intramolecular bonds of ligands like how CONECT is with PDB.  Perhaps as a
parsing mode that only creates the intramolecular bonds needed for
ligands?  A good test is whether one can read in a format, write out a
different format and convey the same information either direction.

+1 to generalize SSBond -> Bond and perhaps adding in the other data
members described by _struct_conn for symmetry, etc.

On Wed, Mar 2, 2016 at 7:46 PM, Andreas Prlic <notifications@github.com>
wrote:

> +1
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/biojava/biojava/issues/341#issuecomment-191534652>.
>



-- 
Matt Larson, PhD
Madison, WI  53705 U.S.A.

**Comment by josemduarte** [comment]
The thing is that before pull request #379, ligand bonds from chemical component files __were already parsed__ in `BondMaker` class (called from both `PDBFileParser` and `SimpleMmCifConsumer`). The inconsistency was that the bonds were being added only to atoms and not to Structure connections (through `Structure.getConnections()`). As I argue above, I think `Structure.getConnections()` is not the best way to keep the bonds, so I'd rather deprecate it and get the bonds through `Atom.getBonds()`.

This branch demonstrates how the test `TestParseMmCIFLigands` that you introduced works with `Atom.getBonds()` with some adaptations: https://github.com/josemduarte/biojava/tree/bondsRewrite

> It would be nice if there was an equivalent for the mmCIF where is only the intramolecular bonds of ligands like how CONECT is with PDB. Perhaps as a parsing mode that only creates the intramolecular bonds needed for ligands

We could still add another parsing parameter so that `BondMaker` would only do intramolecular bonds in ligands, but I don't see a good reason for that. 

> A good test is whether one can read in a format, write out a different format and convey the same information either direction.

At the end of the day the most correct way to get the ligand bonds is from the separate chemical component files, so this is extra information not necessarily present in PDB/mmCIF files. We really can't reproduce CONECT records on read/write in general.
