### ISSUE TITLE
AbstractFastqReader should have possibility for stream-based reading

### ISSUE THREAD

**Issue by kerner1000** [biojava/biojava#348]
<code>AbstractFastqReader</code> internally collects the whole file into memory before any access is possible. This is not very desirable in terms of performance.

<code>AbstractFastqReader#read</code> should return an <code>Iterator\<Fastq\></code> instead of <code>Iterable\<Fastq\></code>.

**Comment by heuermh** [comment]
Hello @kerner1000, thank you for the feedback.

That is the tradeoff for the simplest API, [FastqReader.read(File)](http://www.biojava.org/docs/api/org/biojava/nbio/sequencing/io/fastq/FastqReader.html#read(java.io.File)).

If you want streaming access to ```Fastq``` objects, use [FastqReader.stream(Readable, StreamListener)](http://www.biojava.org/docs/api/org/biojava/nbio/sequencing/io/fastq/FastqReader.html#stream(java.lang.Readable,%20org.biojava.nbio.sequencing.io.fastq.StreamListener)).

If you want low-level access to parse tokens, use [FastqReader.parse(Readable, ParseListener)](http://www.biojava.org/docs/api/org/biojava/nbio/sequencing/io/fastq/FastqReader.html#parse(java.lang.Readable,%20org.biojava.nbio.sequencing.io.fastq.ParseListener)).

There are many examples of the FASTQ I/O API in the [cookbook documentation](http://biojava.org/wiki/BioJava:CookBook3:FASTQ), although they appear not to have been updated to use the latest Guava APIs (e.g. InputSupplier has since been deprecated and removed).

**Comment by kerner1000** [comment]
Yes, I saw those examples. And I had troubles as you describe. The <code>FastqReader#parse</code> methods require a <code>Readable</code> instead of <code>Reader</code>. I was not sure how to use this properly.

**Comment by heuermh** [comment]
Lots of things implement [java.lang.Readable](http://docs.oracle.com/javase/7/docs/api/java/lang/Readable.html):  FileReader, InputStreamReader, etc.

```java
FastqReader fastqReader = ...;
try (BufferedReader reader = new BufferedReader(new FileReader(new File("reads.fq")))) {
  fastqReader.parse(reader, new ParseListener() {
      @Override
      public void sequence(final String sequence) { ... }
      //...
    });
}
```

**Comment by kerner1000** [comment]
Yes, you are right of course! I dont remember what was the comiler error I got but I will give it another try, using the low level API. Thanks!

**Comment by sbliven** [comment]
Returning `Iterable` is preferable to `Iterator` since you can use the result directly in foreach loops. You can always just call `read().iterator()` if you need the latter.

**Comment by andreasprlic** [comment]
Can we close this ?

**Comment by heuermh** [comment]
I believe so, thanks!
