### ISSUE TITLE
org.biojava.nbio.genome.parsers.gff.Location union() and intersect() do not work as described in API

### ISSUE THREAD

**Issue by josemduarte** [biojava/biojava#355]
From Christopher Gillies in biojava-l:

I am using version 4.1.0 and I am getting some unexpected behavior from the Location class.

Please see the unit test below. The union operator returns 51227381 as the bioEnd() but it should be 51227382.

```java
Location l1 = Location.fromBio(51227320, 51227381, '+');
Location l2 = Location.fromBio(51227323, 51227382, '+');

Location union = l1.union(l2);
assertEquals(51227320,union.bioStart());
assertEquals(51227382,union.bioEnd());
```

The documentation for the intersection method says that it will return null when there is no overlap for two locations, but the code appears to fail for boundary conditions. The following unit test fails. Shouldn’t the intersection method return null for this test case?

```java
Location l1 = Location.fromBio(100, 200, '+');
Location l2 = Location.fromBio(1, 99, '+');
Location intersection = l1.intersection(l2);
assertNull(intersection);
```

**Comment by josemduarte** [comment]
I've added the test to branch https://github.com/josemduarte/biojava/tree/issue355. The first test does work, the second doesn't and I suspect it is a bug in the `intersection` method.

**Comment by christopher-gillies** [comment]
Thanks Jose. You are correct. The first issue was my mistake.

**Comment by josemduarte** [comment]
What happens is that `Location.fromBio` converts `start`, `end` coordinates to `start-1` and `end` (in case above it would be `l1=99,200`, `l2=0,99`). Based on that then there is an overlap on 99 for your test case above. Could that be the desired behaviour? I don't really know enough about this part of Biojava to judge.

**Comment by christopher-gillies** [comment]
While it is possible that is the desired behavior, I do not think it is. However, I am new to biojava so I could be wrong. But I think this is not the correct behavior because of what the documentation says:

"Internally, location indices are stored in Java "half-open" format: the start is the (origin 0) index of the first symbol in the range; the end is the origin 0 index of the first symbol PAST the end of the range, so that end - start == length. "

So the end coordinate is the first symbol PAST the end range. So l2=[0,99) and 99 is the index of the first symbol PAST the end range. For l1=[99,200) the start is the first symbol in the range. So l2 contains no elements in l1 because the end value is non-inclusive. Therefore, there is no overlap between the two intervals. The length of the intersection result also validates this interpretation. See the code below:

Location l1 = Location.fromBio(100, 200, '+');
Location l2 = Location.fromBio(1, 99, '+');
Location intersection = l1.intersection(l2);
assertEquals(0,intersection.length());

The documentation for the intersect method says: “The maximal location that is contained by both. Returns null if no overlap!”

Based on this I do not think this is the correct behavior.

**Comment by heuermh** [comment]
I also don't know much about the post-1.x biojava code here, but I do know getting this right is hard.  That is why I like to use

**Comment by josemduarte** [comment]
Since #534 we have guava as dependency of the genome module. So it should be easier now to move to the `Range` API to fix this problem.

**Comment by heuermh** [comment]
Some `Range`-based stuff is available under LGPL version 3 or later here
https://github.com/heuermh/dishevelled-bio/tree/master/range/src/main/java/org/dishevelled/bio/range

**Comment by josemduarte** [comment]
Ping @christopher-gillies , could you check things work as you expect after the fix in #567 ?

**Comment by josemduarte** [comment]
The fix from @audrius-apptornado is now in master and bugfixes-4.2. It will go out in 4.2.5 and 5.0

**Comment by audrius-apptornado** [comment]
__________________________________
Your email was received

AppTornado | Sep 03, 2016 04:12AM CEST

Hi,
  
Thank you for contacting us. We have received your email and we are working on responding to you as soon as possible. Please note that our customer support is available from Monday to Friday from 9:00 AM to 17:00 PM (UTC+1:00). 

We thank you for your understanding. 


[[ef17b14792c214a494e8bfed58926ed8105b39f9-785310988]]
