### ISSUE TITLE
Freeze log4j version at 2.3

### ISSUE THREAD

**Issue by sbliven** [biojava/biojava#364]
Recently the log4j version has bounced several times between 2.3 and 2.5.

Version 2.4+ require Java 1.7, and are thus incompatible with our current JDK requirements. I know that some people have advocated for dropping 1.6 support from BioJava. That is a valid suggestion, but for the purposes of this issue lets assume that the current policy of 1.6 support is in effect.

It the discussion of 6071ce2, @josemduarte points out that since log4j is only included at runtime, we could internally agree to use the latest log4j version with a 1.7 jvm for our testing, while still being compatible with downstream users who use 1.6 and provide their own logging implementation. This is true, but goes against the expectations of many tools (e.g. eclipse) and can lead to some surprising runtime errors. Unless log4j 2.5 introduces some *very* compelling new features, I suggest that we revert to 2.3 and freeze at that version.

**Comment by josemduarte** [comment]
I think in our discussion we did agree on upgrading the java version for the next release. We still need to decide whether it will be first to 1.7 and then to 1.8 or directly to 1.8. In any case there is agreement that we should not stay in 1.6 any longer. 

One of the reasons begind upgrading java __is precisely the issue here__: we want to be able to use up-to-date external dependencies without having problems with the java compile level. Perhaps log4j2 is not the most urgent one, I agree there. But most of the other libraries around __are already 1.7+__ and we really want to use the latest up-to-date libraries, now and in the next 6+ months of Biojava development (where more and more libraries are going to be switching over).

In any case even without upgrading java to 1.7 or 1.8, log4j 2.5 __does work__ fine in the current setup, providing your jre is 1.7+. I'd say that's not an enormous requirement as of January 2016. Java 1.6 has been without public updates since April 2013, the likelihood of still having a 1.6 jre around is really small by now.

**Comment by emckee2006** [comment]
Actually it may not be as unlikely as you might think.  It can be somewhat
hard to upgrade jre (and in our case, tomcat) on our customer facing
production servers.  We still speak 1.6 there (with biojava-core and
biojava-align). Hopefully we will finally get a chance to upgrade this
year, but it requires a sizable test overhead...
On Jan 11, 2016 5:10 PM, "Jose Manuel Duarte" <notifications@github.com>
wrote:

I think in our discussion we did agree on upgrading the java version for
the next release. We still need to decide whether it will be first to 1.7
and then to 1.8 or directly to 1.8. In any case there is agreement that we
should not stay in 1.6 any longer.

One of the reasons begind upgrading java *is precisely the issue here*: we
want to be able to use up-to-date external dependencies without having
problems with the java compile level. Perhaps log4j2 is not the most urgent
one, I agree there. But most of the other libraries around *are already
1.7+* and we really want to use the latest up-to-date libraries, now and in
the next 6+ months of Biojava development (where more and more libraries
are going to be switching over).

In any case even without upgrading java to 1.7 or 1.8, log4j 2.5 *does work*
fine in the current setup, providing your jre is 1.7+. I'd say that's not
an enormous requirement as of January 2016. Java 1.6 has been without
public updates since April 2013, the likelihood of still having a 1.6 jre
around is really small by now.

—
Reply to this email directly or view it on GitHub
<https://github.com/biojava/biojava/issues/364#issuecomment-170707351>.

**Comment by andreasprlic** [comment]
We need to move the discussion about what Java version to use to the mailing list...
