### ISSUE TITLE
Include ligands in the MultipleAlignmentJmol

### ISSUE THREAD

**Issue by sbliven** [biojava/biojava#378]
Ligands are currently missing from the MultipleAlignmentJmol.

**Comment by lafita** [comment]
Could be linked to #396, a good way of rewritting the visualization code.

**Comment by lafita** [comment]
Ligands are currently shown in `MultipleAlignmentJmol`. See the [DemoMultipleMc](https://github.com/biojava/biojava/blob/b0e076d931349d07f7190731ab0c3930c0d12d0b/biojava-structure-gui/src/main/java/demo/DemoMultipleMC.java) with structure with ligands, like DHFRs. See the `MultipleAlignmentDisplay` to learn how is it done.

The problem seems to be that **CE-Symm** display is not using this method and is passing the atoms directly, which only include polymer ones. I will try to fix this.

**Comment by lafita** [comment]
Ligands are now shown both for Multiple Alignments and Symmetry Results. A feature still to implement is ligand coloring.
