### ISSUE TITLE
Problems with demos in biojava-structure-gui

### ISSUE THREAD

**Issue by andreasprlic** [biojava/biojava#383]
There are a few problems with the demos in the biojava-structure-gui module. 

- There are references to classes from the test- code.
- DemoCeSym currently does not work

**Comment by andreasprlic** [comment]
there are some patches now in my branch, however there is still the problem that in DemoCeSymm some Group objects don't have a Chain reference and FileConvert.toPDB() fails, when trying to visualise the result.

**Comment by lafita** [comment]
@andreasprlic, @sbliven and I noticed that when doing any structural alignment, there were some groups without chains that were giving a ´NullPointerException´ when shown in Jmol. The bug was introduced in 818758a, because @josemduarte added the feature that when cloning Groups, the altLocs are also cloned. That was generating in the ´PDBFileParser´ and ´mmCiff Parser´ Groups with two levels of altLocs (which means, that Groups that were altLocs had also altLocs, but with null chains as parents). This is now fixed with two commits (one for PDB files and other for mmCiff), which are ff66c26573022cfba2cfa6a025b58435b5c9a960 and cb0a7e5b769be835d1cba3a671ce7595f3b6997e. This should be fixed now!

**Comment by josemduarte** [comment]
So this can be closed now, right? I've checked `DemoCeSymm` and it works fine.

Note that #387 was needed for demos to compile and run with default config.

**Comment by josemduarte** [comment]
Actually it seems that `DemoMultipleAlignmentJmol` still needs to be fixed.

**Comment by lafita** [comment]
I deleted **DemoMultipleAlignmentJmol** in 09b19f910796d51238de94d84e12192f44c8d218 because there are 3 other demos that trigger a **MultipleAlignmentJmol** and already show how it works.
