### ISSUE TITLE
Change the DEFAULT ChemCompProvider to a complete one

### ISSUE THREAD

**Issue by lafita** [biojava/biojava#397]
There have been a lot of discussion lately around which **ChemComp** Provider to set as **DEFAULT**. This issue is intended to summarize the other comments about it and promote more discussion.

On the one hand, the chemical component information is essential in many cases, and can produce unexpected behaviors like in #377. It is also used in defining the type of `Group` of a Structure (Nucleotide, AminoAcid or Hetatom), which is needed for obtaining the representative Atom array #313 and secondary structure calculation #337. Other discussions are in #314 and #294.

On the other hand, the `DownloadChemCompProvider` is slower than the `ReducedChemCompProvider` and more susceptible to Network settings (less robust), but it ensures that the chemical component information is complete (unless it fails to download it).

Now that the fallback behavior of the `DownloadChemCompProvider` has been implemented #315, setting it as the default would only mean a slower `Structure` parsing, which would only be noticed when downloading a single `Structure` (for larger sets the ChemComp information would be cached).

**Comment by josemduarte** [comment]
I definitely support `DownloadChemCompProvider` as the default. That is the most sensible setting for most uses. Not having the full chemical description of molecules can lead to many problems as you explain, the non-expert user will be very confused if that happens. 

Only when the user is really concerned about performance or lack of network access then it makes sense to explicitly set the `ReducedChemCompProvider`. The user will then know that if something doesn't work it is because he set the reduced provider.

**Comment by andreasprlic** [comment]
Let's review the new ZipChemCompProvider, perhaps that should be the new default...

**Comment by andreasprlic** [comment]
To explain some more, I think the ZipChemCompProvider should be modified to fetch components.cif.gz at first init and convert it into a zip file. Essentially this can be a replacement for the AllChemCompProvider, without needing to store the whole dictionary in memory.

**Comment by lafita** [comment]
I agree with any solution (implementation) that ensures having all the Chemical Component information when needed as the default. The actual default restricts the available information to improve the efficiency.

**Comment by andreasprlic** [comment]
fixed
