### ISSUE TITLE
StructureIO.getStructure(pdbId) fails if a file with pdb id present in working dir

### ISSUE THREAD

**Issue by josemduarte** [biojava/biojava#398]
Following pull request #376 there is an issue with how the structure identifier string is detected to be a file. If a file happens to be present in working dir with a name coinciding with a PDB id, then `StructureIO.getStructure(pdbId)` tries to read the file instead of going to the actual PDB id. We've just seen this (unlikely) issue happening in real life and it was very confusing.

A better behavior would be to try first if the string matches a pdb id and only if it doesn't try to see if a file with that name is present.

I've added a test to demonstrate the issue here: josemduarte/biojava@f4a86f2d976e18bb9bbe2823b81cbd95c50319ea

**Comment by josemduarte** [comment]
So it seems that the strings that `StructureIO.get(String)` takes can be quite complicated, from `SubstructureIdentifier` docs:
```java
/**
 * 
 * <p>Identifiers should adhere to the following specification, although some
 * additional forms may be tolerated where unambiguous for backwards compatibility.
 * <pre>
 * 		name          := pdbID
 * 		               | pdbID '.' chainID
 * 		               | pdbID '.' range
 * 		range         := range (',' range)?
 * 		               | chainID
 * 		               | chainID '_' resNum '-' resNum
 * 		pdbID         := [0-9][a-zA-Z0-9]{3}
 * 		chainID       := [a-zA-Z0-9]+
 * 		resNum        := [-+]?[0-9]+[A-Za-z]?
 * </pre>
 * For example:
 * <pre>
 * 		1TIM                            #whole structure
 * 		1tim                            #same as above
 * 		4HHB.C                          #single chain
 * 		3AA0.A,B                        #two chains
 * 		4GCR.A_1-40                     #substructure
 *      3iek.A_17-28,A_56-294,A_320-377 #substructure of 3 disjoint parts
 * </pre>
 * More options may be added to the specification at a future time.
*/
```
The only way to fix this would be to use the same regex as used in `SubstructureIdentifier` before trying to see whether the given string exists as a file.

Could you take a look when you have some time @sbliven ? Thanks!

By the way thanks @abradle for finding the issue, it wasn't an obvious one...

**Comment by josemduarte** [comment]
A possible and very easy solution for this is simply adding a new method `StructureIO.getStructure(File)` that deals with files as inputs, then removing the support for files in method `StructureIO.getStructure(String)`. I think that'd be quite a clean solution and easy to implement. That wouldn't break current code, would it?

**Comment by andreasprlic** [comment]
To me this feels more like a feature than a bug.

**Comment by sbliven** [comment]
Ok, sorry for the slow response on this.

First of all, since the merge `StructureIO.getStructure` merely delegates to `AtomCache.getStructure`, with the list of accepted rules coming ultimately from `StructureName`. It is questionable whether StructureIO is even needed anymore; it seems to function primarily as a singleton AtomCache.

My goal in StructureName was to be as inclusive as possible, so that we could use it for arbitrary user input and it would do the right thing. This is tough for ambiguous cases like filenames.

Currently the resolution goes something like this:
1. Match id against regular expressions for known schemes, e.g. SCOP
2. Try parsing the id as a URL (can include file:// urls)
3. Try treating the id as a File. If it exists or the parent folder exists, it is treated as a filename. (Checking the parent may not be a useful feature, but probably doesn't lead to false positives.)
4. Default to PDB ID

Rather than defaulting to PDB, it might make sense to make the PassThroughIdentifier the default (does nothing except store the input string). However, I'm not sure whether we want to swap the priority of 3 & 4, as @josemduarte seems to be suggesting. If a file exists, isn't it more likely to be a PDB/mmCIF file than anything else?

Instead, perhaps we should add syntax to make it less ambiguous. Several places use a fixed prefix, such as "PDP:". We could "PDB:" (or "rcsb://", as used in NGL) to force an identifier to unambiguously refer to a PDB ID. The "file://" url-scheme already forces an identifier to be treated as a filename (although this requires an absolute path according to the spec, so the File-based parsing is more general than the URL-based parsing). In this way, users can take the uncertainty out of the identifier guessing.

**Comment by josemduarte** [comment]
I've added some logging that doesn't fix the issue but adds some warnings for the most common case of pdb id being passed and file present in working dir

**Comment by andreasprlic** [comment]
I still think it is a feature and not a bug. If a PDB file is in the work directory that is either intentionally, or a messy file organization :-)

**Comment by josemduarte** [comment]
Tell that to @abradle who went crazy a whole morning because he had a file with some garbage in his working dir that happened to be named as a pdb id ;) Things were failing in ways that were very difficult to understand...
