### ISSUE TITLE
biojava-structure-gui still requires biojava specific maven repo

### ISSUE THREAD

**Issue by andreasprlic** [biojava/biojava#459]
For some reason there is still a dependency in biojava-structure-gui to a version of javaws, that is hosted on the biojava specific Maven repo. Let's point it to the system's javaws with

```xml
<dependencies>
    <dependency>
      <groupId>javax.jnlp</groupId>
      <artifactId>jnlp-api</artifactId>
      <version>7.0</version>
      <scope>system</scope>
      <systemPath>${java.home}/lib/javaws.jar</systemPath>
    </dependency>
  </dependencies>
```

see also http://stackoverflow.com/questions/4645104/how-to-bundle-jnlp-api-with-maven-project

**Comment by phidias51** [comment]
Just out of curiosity, is there any reason to include javaws?

**Comment by andreasprlic** [comment]
The structure alignments UI can get launched via javaws. In the structure-gui there is a PersistentConfig class that can store user configuration locally between javaws sessions.

**Comment by josemduarte** [comment]
A note on this: in Linux the openjdk packages don't contain the java web services libs and thus the build fails. 

The java jnlp stuff is in a separate package: `icedtea-8-plugin` and `icedtea-netx`. The jar file equivalent to `javaws.jar` is then located in `/usr/share/icedtea-web/netx.jar`. I then created a symlink to be able to build biojava with maven:

```shell
sudo ln -s /usr/share/icedtea-web/netx.jar /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/javaws.jar
```

Another possible workaround is using the oracle jdk packages.

**Comment by andreasprlic** [comment]
Actually considering this, I think we should remove the javaws dependencies in the structure-ui code.

**Comment by josemduarte** [comment]
Yes this is going to be an issue whenever we build in linux servers with openjdk... 

If we can do without the dependency, that would the best solution.

**Comment by andreasprlic** [comment]
agreed. to prevent this pain, let's just remove this minor feature.

**Comment by phidias51** [comment]
I'm not sure who the users are for the structure-ui application. But it
strikes me that there are a number of potential solutions for distributing
the viewer and it might be worth asking the community to see which one best
fits the need. Here are a couple ideas:

   - Launching the viewer from the command line, or from a shell script, or
   as a double-clickable jar. This is probably the simplest solution, but not
   the most user-friendly for non-technical users since you have to have the
   appropriate version of Java installed.
   - The Java Packager
   <https://docs.oracle.com/javase/8/docs/technotes/guides/deploy/packager.html>
   creates a native launcher for applications and packages the appropriate
   version of Java for the application. This is more complex but gives you a
   more finished application that can be distributed via the desktop app
   stores.  The packager can also create a clickable distribution.

Cheers,

Mark

**Comment by sbliven** [comment]
+1 drop javaws

We already have a pretty friendly binary being built with the protein-comparison-tool module.

**Comment by josemduarte** [comment]
I think this can be closed, can't it?
