### ISSUE TITLE
Better support BIO: identifiers in CE-Symm

### ISSUE THREAD

**Issue by sbliven** [biojava/biojava#462]
Loading a structure from a biological assembly (e.g. 'BIO:1U7G:1') results in a multi-model structure. However, CE-Symm seems to be using only the first model as input.

It's not quite clear to me where this should be fixed:
- Flatten BIO: structures by renaming chains?
- CE-Symm 3.0 algorithms for integrated quaternary/tertiary symmetry detection
- UI code uses all models sequentially when generating the Atom[]

I know we don't officially support quaternary symmetry in CE-Symm, but the fact that it just works most of the time (at worst requiring manually ordering the chains) makes me think that BIO support would be nice.

**Comment by lafita** [comment]
After looking closely at the `CE-Symm` input and the `Jmol` display needs, we would need both **first** and **third** options. The **second** option is only needed so that the user does not need to specify the order of chains and to improve efficiency, but it is not essential for the support.

We need to use all models sequentially when generating the representative `Atom[]` array. This can be easily done with the current code and will allow obtaining the correct results and statistics.

We also need to flatten BIO structures by renaming chains, so that they can be unambiguously selected with `Jmol` syntax. The problem is that we would need multiple-letter chain IDs, and now we are passing the structures to `Jmol` in **PDB** format. The current `Jmol` version we are using in `Biojava` has a few bugs in **mmCIF** support (that were solved in later releases), so we would need to update `Jmol`. Unfortunately, we are using the latest `Jmol` release in **maven central**, and later releases were not uploaded (we would need version `14.4.4`).

Updating `Jmol` and passing structures to it as **mmCIF** is an important enhancement, related to #201. We were also discussing factoring out the display code to use any viewer #396 #393.

**Comment by josemduarte** [comment]
As part of the pull request I'm working on to simplify the interface to get bioassemblies (see #476), I could add a new parameter that returns either the current multi-model bioassemblies or the flattened bioassembly (i.e. a single model, but renamed chains for symmetry partners).
