### ISSUE TITLE
AtomCache does not locally cache mmtf files

### ISSUE THREAD

**Issue by andreasprlic** [biojava/biojava#468]
Currently the AtomCache fetches mmtf files on the fly. Would be nice to also add the same caching behaviour as we have for pdb and mmcif files. (even with fetching on the fly it is much faster than parsing locally cached mmcif files).

**Comment by josemduarte** [comment]
Also fetching needs to be implemented so that it follows the different behaviors defined in `org.biojava.nbio.structure.io.LocalPDBDirectory.FetchBehavior`.

An important feature that we would need when caching is to be able to replace cached files with newer versions if they become available (which corresponds to the current `FetchBehavior.FETCH_IF_OUTDATED`)

**Comment by andreasprlic** [comment]
need checksums for mmtf
