### ISSUE TITLE
protein-comparison-tool-5.0.0-SNAPSHOT -outputPDB error

### ISSUE THREAD

**Issue by leonqli** [biojava/biojava#594]
I run the tool in the following way: 
./runCE.sh -pdb1 4hhb.A -pdb2 4hhb.B -autoFetch -pdbFilePath ~/pdbs/ -outputPDB  -outFile a.pdb

Thanks,
Leon 

Protein Comparison Tool 5.0.0-SNAPSHOT 20160324-1541
java.lang.NoSuchMethodException: org.biojava.nbio.structure.align.gui.DisplayAFP.getAtomArray([Lorg.biojava.nbio.structure.Atom;, java.util.List, java.util.List)
    at java.lang.Class.getMethod(Class.java:1786)
    at org.biojava.nbio.structure.align.ce.GuiWrapper.getAtomArray(GuiWrapper.java:190)
    at org.biojava.nbio.structure.align.util.AFPAlignmentDisplay.createArtificalStructure(AFPAlignmentDisplay.java:413)
    at org.biojava.nbio.structure.align.ce.AbstractUserArgumentProcessor.checkWriteFile(AbstractUserArgumentProcessor.java:591)
    at org.biojava.nbio.structure.align.ce.AbstractUserArgumentProcessor.runPairwise(AbstractUserArgumentProcessor.java:532)
    at org.biojava.nbio.structure.align.ce.AbstractUserArgumentProcessor.process(AbstractUserArgumentProcessor.java:197)
    at org.biojava.nbio.structure.align.ce.CeMain.main(CeMain.java:79)

**Comment by josemduarte** [comment]
Thanks for the report! It looks like this is a bug in `org.biojava.nbio.structure.align.ce.GuiWrapper`, it tries to invoke an `org.biojava.nbio.structure.align.gui.StructureAlignmentDisplay` method (`prepareGroupsForDisplay`) that doesn't exist anymore. @lafita @sbliven could you guys have a look?

This highlights a problem in the design of the `GuiWrapper` class: it will not show errors at compile time after refactoring of method names. Could this be avoided somehow? Is there a reason to use reflection instead of direct calls here?

**Comment by andreasprlic** [comment]
Reflection is used to work around maven dependency tree issues.

**Comment by josemduarte** [comment]
It could simply be avoided by moving `GUIWrapper` and `AFPAlignmentDisplay` to the GUI package (where they really belong since it is a GUI application anyway). Also `AbstractUserArgumentProcessor` could go to a utils module to make things easier. The current solution is doing exactly that but through an unsafe mechanism instead of using the much safer maven procedure.

**Comment by lafita** [comment]
If I remember correctly the reason for having GUIWrapper and AFPAlignmentDisplay in the structure module is to be able to show a window with the result of a structural alignment obtained from the command line tool, which is in the structure module.

In my opinion the problem is the location of the command line tool, which should not be in the structure module if it requires GUI features. As we started discussing in #559, command line tools could be moved to a new module or repository, so that dependencies can be managed independently for each of them, and this is an example where it would be beneficial.

**Comment by sbliven** [comment]
I rather liked the reflection feature. It allows dynamically adding GUI features based on what's available in the classpath, so users can trade off binary size vs features. Plus it made debugging the structure package easier.

**Comment by sbliven** [comment]
Let's fix GUIWrapper now and discuss rearranging CLI tools in #559.

**Comment by cgorgulla** [comment]
I have a similar problem as @leonqli. Is there some workaround or some beta version which would allow me to use the tool at the moment? Or does an older version does not have this problem?

**Comment by lafita** [comment]
Note that biojava-5 has not still been released - we are working towards the release and will fix bugs like this one.

For the moment, you can use biojava-4, which does not have this problem. The newest biojava-4 release is 4.2.6 (https://github.com/biojava/biojava/releases/tag/biojava-4.2.6).

Sorry for the inconvenience and thanks for reporting!

**Comment by josemduarte** [comment]
The issue originally reported above seems to have been fixed. Let's continue the discussion of CLI tools in #559

**Comment by lafita** [comment]
This was actually not fixed. I fixed the `GUIWrapper` bug, so that the tool works again and submitted a PR.

@sbliven although it allows more flexibility and to reduce the binary size, it complicated a lot the code and makes debugging incredibly tedious. I think we should go for simplicity and make this more modular, i.e. separate the source code from the tools. Let's continue the discussion on #559
