### ISSUE TITLE
Drop blast parser

### ISSUE THREAD

**Issue by sbliven** [biojava/biojava#608]
There was some discussion recently about whether Biojava 5 should contain the Blast parser. The argument against it (put forth by @andreasprlic) was that it is possible to parse XML in a very minimal amount of code using standard libaries. This would also get around some of the issues with how the search.io package is currently implemented (#354 and #607).

Can someone provide some sample code for how one would parse and use blastxml without the search.io package? Also, would we be willing to drop support for blast tabular output?

**Comment by sbliven** [comment]
I'd also be interested in hearing who's actively using the search.io package (@paolopavan?).

**Comment by andreasprlic** [comment]
It is fairly easy to create your own Blast mapping:

'xjc -p blast -dtd  http://www.ncbi.nlm.nih.gov/dtd/NCBI_BlastOutput.dtd'

**Comment by sbliven** [comment]
It looks like the xjc approach generates some light beans to store all the info. Converting to Biojava objects is still an extra step and might be worth keeping around. So while parsing the file is easy, using the returned object with BioJava could run into the same kind of problems addressed by #354.

**Comment by andreasprlic** [comment]
I'd say it should be up to the user what to do with a blast output. The lightweight beans created with xjc allow to access any field in the output. Creating sequence objects from that is not that hard.   My vote is 
to not have this as part of Biojava, since I just don't see the use case. Any other opinions?

**Comment by emckee2006** [comment]
If it is at all common to parse Blast output and create sequence objects
and such, then why force users to constantly rewrite the code to do so?  It
sounds like a fairly trivial addition to include it, so why not?

**Comment by paolopavan** [comment]
Thank you Spencer for the mention, actually this discussion is escaped to
me. Where this have been done?

I vote to maintain the whole module since I'm a heavy user of it.
It is not for the parsing itself which may or may be not straightforward
but because it defines common data structures to manage Search results
which abstracts from the used program itself. Of course in my opinion this
is the main task that a computer library must accomplish.
One person that today uses Blast may easily switch to Diamond or Lambda in
theory without changing any line of code.

The second reason is that the module is generic regarding the parsers used
and easy to use (in my opinion, even easier than any other solution). In
fact it is thought to define for the user a unique layer of interaction
which is able to deal with any parser implementation which is hidden in the
gut.

To make an example, the way to use it is just:

SearchIO reader = new SearchIO(new File("BlastReport.blastxml"));

// results are easily accessed through nested iterators that follow the concept
// that in a report there are one one or many results,
// every result contains one or many hits, one hit contains one or more hsp:
for (Result result: reader){ ... }



2016-11-28 17:03 GMT+01:00 emckee2006 <notifications@github.com>:

**Comment by sbliven** [comment]
Closing due to lack of consensus on how to best solve #354.
