### ISSUE TITLE
Biojava API

### ISSUE THREAD

**Issue by rmoszczynski** [biojava/biojava#609]
Biojava offers a lot of functionality. But it can be used only on the JVM platform. Maybe also in the console by using the reduced cli interface.

What if one want to use it from a totally different programming environment? Maybe a web application written in Ruby or Python or even from mobile apps on iOS or JavaScript?

There is a generic solution for it providing a Restful JSON API exposing some of the biojava functionality over HTTP. This can be accessed from every programming environment and using one interface for that.

It is a analogue use case if you look at Apache Lucene and Elasticsearch. Lucene is a Java information retrieval library. Elasticearch exposes the functionality over a JSON Restful API and enhances it.

We can even go an step further and use the other Bio* libs for Ruby, Python etc. and exposures it over one unified API instead of porting the algorithms between the platforms. The API server could be installed in a local network so the applications not necessarily has to access internet directly.

In this way we could build a Bio API providing a lot of functionality available to everyone.

What do you think about it?

**Comment by phidias51** [comment]
The Lucene/Elasticsearch idea sounds useful, although I should point out, that the first part of your reasoning is specious.  

You can use BioJava from the console and call any class/method (the CLI isn't a "reduced interface"). You can do this from Java's console (called JShell).  You can also do this from the Groovy Console, the JavaScript console (known as JRunScript), JRuby's Console (known as jirb), and Jython's console. In fact most of the scripting languages on the JVM support a CLI console, thus making any Java library (or native library) scriptable. 

As for mobile apps, you can include BioJava in any Android app, and you can make cross platform (iOS/Android apps) using JavaFX. There are also tools like Code Name One, and RoboVM that can help with this. I don't do a lot of cross platform mobile development, but definitely worth a look.

Making a RESTful app using BioJava is likewise doable. You can use Spring Boot, Grails, Ratpack and other frameworks to provide the RESTful interface.  In BioGroovy (which uses BioJava) you can parse and load data into a database with about 10 lines of code. BioGroovy also makes it fairly trivial to create domain classes in Grails. This means if you want a full-stack web app, you can do that fairly easily, and use Grails initializer to load data into your web app. You can use Grails scaffolding to automatically create your UI.  If you want a headless REST app, you simply tell grails to generate a REST app, instead of a web app.

You are, in fact, spoiled for choices when it comes to using BioJava in JVM applications.

**Comment by heuermh** [comment]
Does anyone else remember BioCORBA?  ;)

**Comment by sbliven** [comment]
Creating a clean rest interface requires a lot of work. I started the http://github.com/biojava/biojava-http project at a the BOSC Codefest last summer with the intention to provide a REST API, but currently it's only providing things that I'm personally using (e.g. some structural methods). However, for that limited subset of biojava it is deployed at http://cesymm.rcsb.org/. Expanding this to the rest of biojava would be awesome.

**Comment by rmoszczynski** [comment]
Ah, very cool! That's what I meant. Sure it is a lot of work but if there is need for such an API maybe we should work on it.

Maybe we could start with a list of feature requests. I have no idea what functionality users need.

**Comment by andylaw** [comment]
"if there is need for such an API maybe we should work on it”

and

"I have no idea what functionality users need”

are warning flags as far as I am concerned.


> On 28 Nov 2016, at 11:54, Robert Moszczynski <notifications@github.com> wrote:
> 
> Ah, very cool! That's what I meant. Sure it is a lot of work but if there is need for such an API maybe we should work on it.
> 
> Maybe we could start with a list of feature requests. I have no idea what functionality users need.
> 
> —

Later,

Andy



-- 
The University of Edinburgh is a charitable body, registered in
Scotland, with registration number SC005336.

**Comment by sbliven** [comment]
I suggest starting new issues at the biojava-http project for any feature requests

**Comment by andreasprlic** [comment]
Nowadays I am using BioJava almost entirely on the backend of some web services. It is very easy to wrap in whatever way is needed. I don't think much work is needed here.

**Comment by rmoszczynski** [comment]
@andreasprlic 

Ok, this is the answer I waited for. Apparently there is no massive demand on exposing the functionality over a RESTful interface and there are other urgent issues where one can better invest the time.

And if then we can suggest some on the biojava-http as @sbliven proposed. Maybe it is a topic for the future.

Thanks!
