### ISSUE TITLE
Differences between DSSP implementation and PDB DSSP reference

### ISSUE THREAD

**Issue by briskaa** [biojava/biojava#627]
I am seeing differences in the secondary structure assignments generated by the BioJava class SecStrucCalc and those returned from the PDB via the  DSSPParser.fetch() method in about a third of test structures.

These differences persist even after applying the recent pull request https://github.com/biojava/biojava/pull/626 which addressed an issue with structures containing insertion codes.

I'm attaching a demo program that performs the comparison against a list of PDB ids and provides some summary information.  I am also attaching my list of PDB ids plus the summary of differences after comparing 3577 structures.

[SecStrucCalcBug.java.txt](https://github.com/biojava/biojava/files/702656/SecStrucCalcBug.java.txt)
[differences.txt](https://github.com/biojava/biojava/files/702650/differences.txt)
[pdbids.txt](https://github.com/biojava/biojava/files/702651/pdbids.txt)

**Comment by lafita** [comment]
Thank you for submitting the issue. We had not done such exhaustive testing of the BioJava DSSP implementation, so this is very much appreciated.

When we did our implementation, we followed the theoretical explanations in the original DSSP article, rather than porting the code from the original DSSP implementation in C, so some differences are expected. There are also different versions of the DSSP program, and they explicitly mention that some differences may occur across versions. However, from what you report, I think it is an issue we should address, since the differences in SS assignment are of all types and affect a large percentage of structures. 

I think the next step we have to follow is to address it by looking at the individual cases and trying to reason why the two assignments differ, and in case they do, if the differences are important enough to fix them. 

I analyzed the first 10 structures, from which 4 contain differences in the assignment:
<pre>
> Differences for structure 4FFJ
Residue 24 BIOJAVA_ASSIGNMENT: T - DSSP_ASSIGNMENT: S
Residue 25 BIOJAVA_ASSIGNMENT: T - DSSP_ASSIGNMENT:  
Residue 26 BIOJAVA_ASSIGNMENT: T - DSSP_ASSIGNMENT:  
> Differences for structure 3CT9
Residue 102 BIOJAVA_ASSIGNMENT: I - DSSP_ASSIGNMENT: T
Residue 103 BIOJAVA_ASSIGNMENT: I - DSSP_ASSIGNMENT: T
Residue 104 BIOJAVA_ASSIGNMENT: I - DSSP_ASSIGNMENT: T
Residue 105 BIOJAVA_ASSIGNMENT: I - DSSP_ASSIGNMENT: T
> Differences for structure 4IO1
Residue 224 BIOJAVA_ASSIGNMENT: E - DSSP_ASSIGNMENT:  
> Differences for structure 1IVH
Residue 102 BIOJAVA_ASSIGNMENT: I - DSSP_ASSIGNMENT: T
Residue 103 BIOJAVA_ASSIGNMENT: I - DSSP_ASSIGNMENT: T
Residue 104 BIOJAVA_ASSIGNMENT: I - DSSP_ASSIGNMENT: T
Residue 258 BIOJAVA_ASSIGNMENT: G - DSSP_ASSIGNMENT: T
Residue 259 BIOJAVA_ASSIGNMENT: G - DSSP_ASSIGNMENT: T
</pre>

- **4FFJ**: the region 24-26 is just before two residues missing in sequence (http://www.rcsb.org/pdb/explore/remediatedSequence.do?structureId=4FFJ) . I am not sure, but DSSP may treat missing residues differently.
- **3CT9**: the residues 102-105 are at the start of an alpha helix, and when looking at the structure, I think the pi-helix assignment of BioJava is also right (or even better), since we observe a wider turn. We may need a special case for pi-helices at the terminal of alpha-helix having a minimum length, but I do not think this is an important difference.

![3ct9_pi-helix](https://cloud.githubusercontent.com/assets/11161522/21929462/e6e2e99a-d990-11e6-8e72-c084afb49b42.png).

- **4IO1**: residue 224 is at the C-terminal position (http://www.rcsb.org/pdb/explore/remediatedSequence.do?structureId=4IO1), and the previous residues form a large strand. It could be that terminal residues are treated differently in DSSP, or even removed from strand assignment.

- **1IVH**: residues 102-104 are in between an alpha-helix, same case as 3CT9. The assignment for 258-259 in the PDB website is H and T (http://www.rcsb.org/pdb/explore/remediatedSequence.do?structureId=1IVH) so it also does not match any of the DSSP or BioJava assignments, and they are in between two alpha-helices. I think it is not important.

One thing that could be compared, and that should be the same between BioJava and DSSP always, is the calculation of H-bonds between residues. We did some more extensive testing on that and it was matching, but we currently do not have a test.

**Comment by lafita** [comment]
Hi @briskaa, I thought that an easy thing we can do with a slight modification on the script you created is to calculate the relative frequency of the disagreements, that is, the number of disagreements divided by the total number of assignments. 

I would expect them to be less than 1%. Then, we could identify the structures with a disagreement higher than 10%, for example, and take a closer look at it to identify the possible bugs in the code using them.
