### ISSUE TITLE
MmtfStructureReader inserts X for unobserved residues in the structure

### ISSUE THREAD

**Issue by pwrose** [biojava/biojava#671]
MmtfStructureReader does not create correct seqResSequence. The getSeqResSequence() method returns a sequence with XXX for positions that are not observed in the coordinates, e.g., 1STP: XXXXXXXXXXXXAEAGITGTWY...

**Comment by lafita** [comment]
I put the test I created for this issue during the MMTF workshop in a new branch in the biojava/biojava repo:

https://github.com/biojava/biojava/tree/mmtf

The new test that currently fails due to the X in the SEQRES is:

`biojava-structure/src/test/java/org/biojava/nbio/structure/io/mmtf/TestMmtfStructureReader.java`

Some debugging on the parsing should find the code responsible for the bug.
