### ISSUE TITLE
QuatSymmetryResults.isPseudoSymmetry() is always false

### ISSUE THREAD

**Issue by josemduarte** [biojava/biojava#708]
It looks like the flag is never set to true in the cases where there is pseudosymmetry. This test actuall has a TODO note for that: https://github.com/biojava/biojava/blob/5f138f314712c2a5fd3950f1b034dae7661231a8/biojava-integrationtest/src/test/java/org/biojava/nbio/structure/test/symmetry/TestQuatSymmetryDetectorExamples.java#L95

**Comment by josemduarte** [comment]
A question here is when should a symmetry result be pseudo-symmetric and when should it be pseudo-stoichiometric. I would say both have the same meaning. 

For pseudostoichiometry, this is what we are doing:

https://github.com/biojava/biojava/blob/359dce819e7678879ae41301b11fa268f92e81d1/biojava-structure/src/main/java/org/biojava/nbio/structure/cluster/SubunitClusterUtils.java#L57-L74

i.e. whenever the method for clustering was `STRUCTURE` then we call it pseudostoichiometric. Why such a definition? what if we clustered by the `SEQUENCE` method, shouldn't that be pseudostoichiometric too?

In my understanding pseudosymmetry/pseudostoichiometry should be true whenever some clustering happened (either by `SEQUENCE` or by `STRUCTURE`)

**Comment by josemduarte** [comment]
After some research, it looks like this combination is possible:
```
isPseudoStoichiometry=true
isPseudoSymmetric=false
```
which happens whenever the stoichiometry is based on clustered subunits, but there's no symmetry detected on clustered subunits.

This combination is not possible:
```
isPseudoStoichiometry=false
isPseudoSymmetric=true
```

**Comment by josemduarte** [comment]
I'd argue that the combination
```
isPseudoStoichiometry=true
isPseudoSymmetric=false
```
doesn't add much value and that we could drop `isPseudoSymmetric` to simplify the code. I'll submit a PR for that.

**Comment by lafita** [comment]
I agree with that, I think that if there is pseudo-stoichiometry there has to be pseudo-symmetry. 

I think the original idea for splitting them was that pseudo-stoichiometry depends on the clustering algorithm and pseudo-symmetry depends on the symmetry detection algorithm, so they could differ. However, I would say that biologically it makes little sense, so let's keep pseudo-stoichiometry only.

> i.e. whenever the method for clustering was `STRUCTURE` then we call it pseudostoichiometric. Why such a definition? what if we clustered by the `SEQUENCE` method, shouldn't that be pseudostoichiometric too?
> In my understanding pseudosymmetry/pseudostoichiometry should be true whenever some clustering happened (either by `SEQUENCE` or by `STRUCTURE`)

This is because the `SEQUENCE` clustering is only used to account for small differences of the sequences (like 95% sequence identity), and pseudo-stoichiometry is only considered when the sequence similarities were lower and structural clustering was used. This is the original idea, I agree that sequence clustering could also be considered pseudo-stoichiometry.
