### ISSUE TITLE
calcLocalSymmetries works on a cluster level, not subunit level

### ISSUE THREAD

**Issue by biocryst** [biojava/biojava#719]
In the current implementation a local symmetry can only be detected, if

1) the assembly contains multiple clusters;
2) all subunits in a cluster (or clusters) are related by a symmetry axis.

(see https://github.com/biojava/biojava/blob/32255b15d7af3f8eb550e05d3ef161e0ab3dfff8/biojava-structure/src/main/java/org/biojava/nbio/structure/symmetry/core/QuatSymmetryDetector.java#L185 and below)

These are rarely satisfied in practice. See PDB 3L28 as an example of what is missed. It is a homo 6-mer (so one cluster in total) with two local C2 axes (so only 2 out of 6 subunits are related for each symmetry). http://www.rcsb.org/pdb/explore/jmol.do?structureId=3L28&bionumber=1

Using power-set of subunits would be a quick fix, although terribly inefficient.

**Comment by lafita** [comment]
The power-set of subunits, instead of subunit clusters, was used before, but it meant that the algorithm scaled exponentially on the number of subunits instead of on the number of subunit clusters. 

This comes from the assumption that homomeric subunits cannot be asymmetric, because it would require unequal engaged interfaces in each monomer. However, there are such cases in the PDB, as you mention, and they could be possible annotation errors. It just occurred to me that this could be a good check for wrongly annotated assemblies.
If we want to detect them again I would suggest a more clever heuristic to find them, rather than the combinatorial way.

**Comment by biocryst** [comment]
Closed due to #726
