### ISSUE TITLE
Make biojava work in Java 9, 10, 11

### ISSUE THREAD

**Issue by josemduarte** [biojava/biojava#804]
@sbliven made some progress in the [java9 branch](/biojava/biojava/tree/java9).

I've tried out the branch and it looks like the main remaining problem is with the jaxb dependency used in a few places (jaxb is apparently not included in 9+).

**Comment by sbliven** [comment]
Oracle announced they will charge for java 8 updates, so this is timely!

https://www.itassetmanagement.net/2018/05/01/oracle-to-charge-for-java-from-jan-2019/

**Comment by paolopavan** [comment]
Does anyone had tried if there are any major compatibility issues? Any
issue of any kind?
I am especially worried about frequent Api changes that will compel to
update my old software too frequently than what I can do. As recalled by
the article, new releases will happen every 6 months. While this could be
interesting when bringing new features in, it can be not sustainable when
those would be API breaking.

Any thoughts?

Il giorno ven 5 ott 2018 alle 08:55 Spencer Bliven <notifications@github.com>
ha scritto:

**Comment by darnells** [comment]
Starting January 2019, Oracle Java (version 11 and beyond) will be a paid-for commercial product and OpenJDK will be the free open-source distribution. OpenJDK has been providing binaries for Windows, macOS, and Linux since JDK 9. I am sure @josemduarte, @sbliven, and others will successfully transition BioJava to Java 11 (the current LTS release) in due time and the majority of us will hop onto OpenJDK 11 sometime in 2019.

@paolopavan, you will want to stick to LTS releases to reduce the frequency of API changes, which are presumably one every 18 months (time will tell if Oracle/OpenJDK stick to that schedule). Otherwise, you could always stick with JDK 8 for as long as your dependencies support it.

**Comment by sbliven** [comment]
@paolopavan The biggest thing was the removal of some packages (e.g. XML). These are now pulled in from maven, so there will be no change for the user. If you want products to be stable (LTS), it looks like the best solution is to migrate them to OpenJDK 11 over the next year or so.
