### ISSUE TITLE
Make CONTRIBUTING.md more detailed 

### ISSUE THREAD

**Issue by lee-mcfaul** [biojava/biojava#828]
I've been poking around the README.md and CONTRIBUTING.MD on master and I have a few questions whose answers I think should be added to the CONTRIBUTING.md document.

1 - Which branch should pull requests be made to when addressing issues.

2 - What is the build/branch model? is it dev -> release -> master? Because it seems like master is the repo with the latest updates by years.

3 - When contributing do you prefer that people fork the repo and create the branch remotely and then submit a pull request? Or do you rather they become part of the project and branch directly on biojava/biojava?

**Comment by lafita** [comment]
Pull requests should be made to `master` branch, please ignore the others. To contribute, fork the repo, create a new branch from master and submit a new pull request. We will review the code and merge it to the main `master` branch.

I agree that we should add more information about this to the documentation and clean up some of the old branches since it might be confusing. Thanks!
