### ISSUE TITLE
Support extended PDB IDs

### ISSUE THREAD

**Issue by sbliven** [biojava/biojava#930]
The wwPDB will run out of 4-character PDB IDs soon and will switch to an extended format: https://www.wwpdb.org/news/news?year=2021#607760112786e73a79c76f9d

The new format will be eight characters prefixed by ‘PDB’, e.g., pdb_00001abc.

Chemical compounds will also run out of 3-letter identifiers soon and will switch to 4-letter identifiers. These are incompatible with the PDB file format.

We should ensure that biojava parsers, data structures, and algorithms can handle both of these changes.

**Comment by aalhossary** [comment]
I can take care of it.
Is there a specific time frame?

**Comment by aalhossary** [comment]
I created a new class `PDBId` that holds a string representing the PDB ID, always in the new (_extended_) format and always in UPPER CASE. It has a convenient constructor, hashCode(), compareTo(), as well as static methods to convert to and from String in the short format (if possible).
Whenever the old PDB Id format is used in `Structure`, `StructureImpl` or `StructureName`, I made conversion that is transparent to the user.

Although I did my best to keep backwards compatibility, having the PDB  ID as a new class instead of a string is a major change with a lot of hassle to keep backwards compatibility. Therefore it is most suitable for the new major release BioJava 6.0.0

One other issue: I found two types of accessor methods `getPdbId()` and `getPDBCode()`. The former is already deprecated a log time ago (since **BioJava 4.2**). I am thinking in **removing it altogether** to leave only `getPDBCode()` and the new `getPDBId()` (notice the case difference between `getPdbId()` and `getPDBId()`).
With the oldest `getPdbId()` removed, there should be no place for confusion.

What do you think about removing it?

**Comment by aalhossary** [comment]
I will also remove `StructureTools.getReducedStructure(Structure s, String chainId)` which is deprecated since BioJava 4.2.0
