### ISSUE TITLE
Missing javadoc

### ISSUE THREAD

**Issue by CoolKangaroo2022** [biojava/biojava#956]
Hello! I find in your [CONTRIBUTING.md](https://github.com/biojava/biojava/blob/600763eebe45a4d215613a1b1e295341b6d3640a/CONTRIBUTING.md#coding) that 
> Javadocs are a must for public facing API methods.

However, I still witness some public methods without Javadocs.
I find likely missing Javadoc in the following files:
* biojava-structure/src/main/java/org/biojava/nbio/structure/align/xml/MultipleAlignmentXMLParser.java
* biojava-structure/src/main/java/org/biojava/nbio/structure/align/pairwise/AlignmentResult.java
* biojava-structure/src/main/java/org/biojava/nbio/structure/xtal/io/TreeMapSpaceGroupWrapper.java
......

Would you like to add Javadoc for these methods, or they are just not that important?
If there is anything I can help with?

**Comment by josemduarte** [comment]
What we write in CONTRIBUTING.md is our aspiration as to the quality of code and docs in the project. Old code might not always adhere to it, but going forward new contributions are expected to follow the guidelines.

As for older code, as you notice there are missing docs in quite a few places. We are always happy to have a new pair of hands to help! If you can provide a Pull Request that would be fantastic.

**Comment by richarda23** [comment]
A good way to create meaningful Javadoc, if there are no unit tests either is to write some unit tests to validate the functionality of the method, what exceptions are thrown, what are valid input arguments.  I've been trying to do this approach recently  with missing javadoc and unit tests in biojava-core/ util package. 

Looking at MultipleAlignmentXMLParser the underlying problem seems to be that all the methods apart from parseXMLfile could have been private, as they are not used anywhere else in Biojava and appear to be helper methods of parseXML, and therefore would not necessarily need Javadoc. Perhaps for such methods, if making them private is not desirable (because risking breaking client code that uses it) is to add some annotation or comment that these methods are not 'API' methods. Quite a few projects now (e.g. junit)  use annotations as a way to indicate which public methods are API (and therefore will be maintained) and which may be changed/altered - e.g. https://junit.org/junit5/docs/current/user-guide/#api-evolution. This could cut down on the amount of missing Javadoc to be completed.

**Comment by josemduarte** [comment]
> Looking at MultipleAlignmentXMLParser the underlying problem seems to be that all the methods apart from parseXMLfile could have been private, as they are not used anywhere else in Biojava and appear to be helper methods of parseXML, and therefore would not necessarily need Javadoc. 

Good point @richarda23 . In this case my guess is that those methods should have been private. Actually we have not released 6.0.0 yet and there's still the opportunity to refactor them to private as a breaking change, with proper documentation in the changelog. 

@lafita it looks this was your code. Would you see any reason not to make them private?

> Perhaps for such methods, if making them private is not desirable (because risking breaking client code that uses it) is to add some annotation or comment that these methods are not 'API' methods. 

I think using API annotations would be wonderful. But it is also quite a task to introduce them for the whole project. I'd be happy to slowly start introducing the annotations if there's consensus to do so.

**Comment by lafita** [comment]
Yes, only the `parseXMLfile` method should be public in this case. Thanks for flagging this!

**Comment by josemduarte** [comment]
Thanks for confirming @lafita . Ok then I will make them private and add that to the 6.0.0 changelog.
