### ISSUE TITLE
PDB Different Date fields

### ISSUE THREAD

**Issue by aalhossary** [biojava/biojava#992]
I am not sure I understand the _exact_ difference between the three dates in structure object. 
According to my understanding:
- **depDate**: The initial deposition date even before the file was released
- **RelDate**: the date of the (first / latest ?) release.
- **ModDate**: some date (?) that is after the `relDate`??????!!!!!!!! (totally confused)

**Comment by aalhossary** [comment]
@JonStargaryen

**Comment by aalhossary** [comment]
For instance **1M3Q** has 

- depDate 2002-06-28
- relDate 2004-02-17
- modDate 2021-10-27

**Comment by JonStargaryen** [comment]
This high-level rendering should provide some clarity: https://www.rcsb.org/versions/1M3Q

Deposition date: when the structure entered the system
Release date: when the structure became publicly available
Modification date: date of the last change to the structure

**Comment by aalhossary** [comment]
Well,
in **5O81** the modDate is the epoch point (1/1/1970 00:00:00), which is a valid but wrong date, and it falls before the deposition date.

in PDBFileParser lines 2873-2883
```Java
		Date modDate = pdbHeader.getModDate();
		if ( modDate.equals(new Date(0)) ) {
			// modification date = deposition date
			Date depositionDate = pdbHeader.getDepDate();

			if (! depositionDate.equals(modDate)){
				// depDate is 0000-00-00
				pdbHeader.setDepDate(depositionDate);
			}

		}
'```
I think there is a bug here.
Why would someone set the DepDate with depositionDate, which came from the same header object!

I understand that it's meant to be 
```
			if (! depositionDate.equals(modDate)){
				// depDate is 0000-00-00
				pdbHeader.setModDate(depositionDate);
			}
```
If this is the case, I would correct it.
Otherwise, then the deposition date should be set to `null` instead of ```new Date(0)```.

**Comment by josemduarte** [comment]
Good catch @aalhossary . That looks like a bug in the CIF parsing. Whilst it looks like PDB parser does fine.

The problem is for the case that only 1 revision date is available, then the CIF parser only assigns the relDate but not the modDate, but it should assign both.

See:

https://github.com/biojava/biojava/blob/baefba4b3e6e73a79355c031f80da825022ad397/biojava-structure/src/main/java/org/biojava/nbio/structure/io/cif/CifStructureConsumerImpl.java#L738

and

https://github.com/biojava/biojava/blob/baefba4b3e6e73a79355c031f80da825022ad397/biojava-structure/src/main/java/org/biojava/nbio/structure/io/cif/CifStructureConsumerImpl.java#L618

**Comment by aalhossary** [comment]
Thank you @josemduarte.
I will work on it -hopefully- tomorrow.

**Comment by aalhossary** [comment]
Fixed and merged
